import { KeyValue } from "@angular/common";
import { Colors } from "src/app/share/values/colors";
import { ChemicalElementModel } from "./chemical-element.model";

export class ChemicalElementsData {
    public static chemicalElements: KeyValue<string, ChemicalElementModel>[] = [
        { key: "H", value: new ChemicalElementModel("Hydrogen", 0, 0, 1, "H", 1.0, Colors.white, Colors.primary, true, true, "s Block") },
        { key: "Li", value: new ChemicalElementModel("Lithium", 0, 1, 3, "Li", 6.9, Colors.primary, Colors.white, false, true) },
        { key: "Na", value: new ChemicalElementModel("Sodium", 0, 2, 11, "Na", 23.0, Colors.primary, Colors.white, false, true) },
        { key: "K", value: new ChemicalElementModel("Potassium", 0, 3, 19, "K", 39.1, Colors.primary, Colors.white, false, true) },
        { key: "Rb", value: new ChemicalElementModel("Rubidium", 0, 4, 37, "Rb", 85.5, Colors.primary, Colors.white, false, true) },
        { key: "Cs", value: new ChemicalElementModel("Caesium", 0, 5, 55, "Cs", 132.9, Colors.primary, Colors.white, false, true) },
        { key: "Fr", value: new ChemicalElementModel("Francium", 0, 6, 87, "Fr", 223, Colors.primary, Colors.white, false, true) },

        { key: "Be", value: new ChemicalElementModel("Beryllium", 1, 1, 4, "Be", 9.0, Colors.primary, Colors.white, true, false) },
        { key: "Mg", value: new ChemicalElementModel("Magnesium", 1, 2, 12, "Mg", 24.3, Colors.primary, Colors.white) },
        { key: "Ca", value: new ChemicalElementModel("Calcium", 1, 3, 20, "Ca", 40.1, Colors.primary, Colors.white) },
        { key: "Sr", value: new ChemicalElementModel("Strontium", 1, 4, 38, "Sr", 87.6, Colors.primary, Colors.white) },
        { key: "Ba", value: new ChemicalElementModel("Barium", 1, 5, 56, "Ba", 137.3, Colors.primary, Colors.white) },
        { key: "Ra", value: new ChemicalElementModel("Radium", 1, 6, 88, "Ra", 226, Colors.primary, Colors.white) },

        { key: "Sc", value: new ChemicalElementModel("	Scandium", 2, 3, 21, "Sc", 45.0, Colors.accentChemistry, Colors.white, true, false, "d Block") },
        { key: "Y", value: new ChemicalElementModel("Yttrium", 2, 4, 39, "Y", 88.9, Colors.accentChemistry, Colors.white) },
        { key: "La", value: new ChemicalElementModel("Lanthanum", 2, 5, 57, "La", 138.9, Colors.accentChemistry, Colors.white) },
        { key: "Ac", value: new ChemicalElementModel("Actinium", 2, 6, 89, "Ac", 227, Colors.accentChemistry, Colors.white) },

        { key: "Ti", value: new ChemicalElementModel("Titanium", 3, 3, 22, "Ti", 47.9, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Zr", value: new ChemicalElementModel("Zirconium", 3, 4, 40, "Zr", 91.2, Colors.accentChemistry, Colors.white) },
        { key: "Hf", value: new ChemicalElementModel("Hafnium", 3, 5, 72, "Hf", 178.5, Colors.accentChemistry, Colors.white) },
        { key: "Rf", value: new ChemicalElementModel("Rutherfordium", 3, 6, 104, "Rf", 261, Colors.accentChemistry, Colors.white) },

        { key: "V", value: new ChemicalElementModel("Vanadium", 4, 3, 23, "V", 50.9, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Nb", value: new ChemicalElementModel("Niobium", 4, 4, 41, "Nb", 92.9, Colors.accentChemistry, Colors.white) },
        { key: "Ta", value: new ChemicalElementModel("Tantalum", 4, 5, 73, "Ta", 180.9, Colors.accentChemistry, Colors.white) },
        { key: "Db", value: new ChemicalElementModel("Dubnium", 4, 6, 105, "Db", 262, Colors.accentChemistry, Colors.white) },

        { key: "Cr", value: new ChemicalElementModel("Chromium", 5, 3, 24, "Cr", 52.0, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Mo", value: new ChemicalElementModel("Molybdenum", 5, 4, 42, "Mo", 96.0, Colors.accentChemistry, Colors.white) },
        { key: "W", value: new ChemicalElementModel("Tungsten", 5, 5, 74, "W", 183.8, Colors.accentChemistry, Colors.white) },
        { key: "Sg", value: new ChemicalElementModel("Seaborgium", 5, 6, 106, "Sg", 266, Colors.accentChemistry, Colors.white) },

        { key: "Mn", value: new ChemicalElementModel("Manganese", 6, 3, 25, "Mn", 54.9, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Tc", value: new ChemicalElementModel("Technetium", 6, 4, 43, "Tc", 98, Colors.accentChemistry, Colors.white) },
        { key: "Re", value: new ChemicalElementModel("Rhenium", 6, 5, 75, "Re", 186.2, Colors.accentChemistry, Colors.white) },
        { key: "Bh", value: new ChemicalElementModel("Bohrium", 6, 6, 107, "Bh", 264, Colors.accentChemistry, Colors.white) },

        { key: "Fe", value: new ChemicalElementModel("Iron", 7, 3, 26, "Fe", 55.8, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Ru", value: new ChemicalElementModel("Ruthenium", 7, 4, 44, "Ru", 101.1, Colors.accentChemistry, Colors.white) },
        { key: "Os", value: new ChemicalElementModel("Osmium", 7, 5, 76, "Os", 190.2, Colors.accentChemistry, Colors.white) },
        { key: "Hs", value: new ChemicalElementModel("Hassium", 7, 6, 108, "Hs", 267, Colors.accentChemistry, Colors.white) },

        { key: "Co", value: new ChemicalElementModel("Cobalt", 8, 3, 27, "Co", 58.9, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Rh", value: new ChemicalElementModel("Rhodium", 8, 4, 45, "Rh", 102.9, Colors.accentChemistry, Colors.white) },
        { key: "Ir", value: new ChemicalElementModel("Iridium", 8, 5, 77, "Ir", 192.2, Colors.accentChemistry, Colors.white) },
        { key: "Mt", value: new ChemicalElementModel("Meitnerium", 8, 6, 109, "Mt", 268, Colors.accentChemistry, Colors.white) },

        { key: "Ni", value: new ChemicalElementModel("Nickel", 9, 3, 28, "Ni", 58.7, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Pd", value: new ChemicalElementModel("Palladium", 9, 4, 46, "Pd", 106.4, Colors.accentChemistry, Colors.white) },
        { key: "Pt", value: new ChemicalElementModel("Platinum", 9, 5, 78, "Pt", 195.1, Colors.accentChemistry, Colors.white) },
        { key: "Ds", value: new ChemicalElementModel("Darmstadtium", 9, 6, 110, "Ds", 271, Colors.accentChemistry, Colors.white) },

        { key: "Cu", value: new ChemicalElementModel("Copper", 10, 3, 29, "Cu", 63.5, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Ag", value: new ChemicalElementModel("Silver", 10, 4, 47, "Ag", 107.9, Colors.accentChemistry, Colors.white) },
        { key: "Au", value: new ChemicalElementModel("Gold", 10, 5, 79, "Au", 197.0, Colors.accentChemistry, Colors.white) },
        { key: "Rg", value: new ChemicalElementModel("Roentgenium", 10, 6, 111, "Rg", 272, Colors.accentChemistry, Colors.white) },

        { key: "Zn", value: new ChemicalElementModel("Zinc", 11, 3, 30, "Zn", 65.4, Colors.accentChemistry, Colors.white, true, false) },
        { key: "Cd", value: new ChemicalElementModel("Cadmium", 11, 4, 48, "Cd", 112.4, Colors.accentChemistry, Colors.white) },
        { key: "Hg", value: new ChemicalElementModel("Mercury", 11, 5, 80, "Hg", 200.6, Colors.accentChemistry, Colors.white) },
        { key: "Cn", value: new ChemicalElementModel("Copernicium", 11, 6, 112, "Cn", 285, Colors.accentChemistry, Colors.white) },

        { key: "B", value: new ChemicalElementModel("Boron", 12, 1, 5, "B", 10.8, Colors.primaryChemistry, Colors.white, true, false, "p Block") },
        { key: "Al", value: new ChemicalElementModel("Aluminium", 12, 2, 13, "Al", 27.0, Colors.primaryChemistry, Colors.white) },
        { key: "Ga", value: new ChemicalElementModel("Gallium", 12, 3, 31, "Ga", 69.7, Colors.primaryChemistry, Colors.white) },
        { key: "In", value: new ChemicalElementModel("Indium", 12, 4, 49, "In", 114.8, Colors.primaryChemistry, Colors.white) },
        { key: "Tl", value: new ChemicalElementModel("Thallium", 12, 5, 81, "Tl", 204.4, Colors.primaryChemistry, Colors.white) },
        { key: "Nh", value: new ChemicalElementModel("Nihonium", 12, 6, 113, "Nh", 280, Colors.primaryChemistry, Colors.white) },

        { key: "C", value: new ChemicalElementModel("Carbon", 13, 1, 6, "C", 12.0, Colors.primaryChemistry, Colors.white, true, false) },
        { key: "Si", value: new ChemicalElementModel("Silicon", 13, 2, 14, "Si", 28.1, Colors.primaryChemistry, Colors.white) },
        { key: "Ge", value: new ChemicalElementModel("Germanium", 13, 3, 32, "Ge", 72.6, Colors.primaryChemistry, Colors.white) },
        { key: "Sn", value: new ChemicalElementModel("Tin", 13, 4, 50, "Sn", 118.7, Colors.primaryChemistry, Colors.white) },
        { key: "Pb", value: new ChemicalElementModel("Lead", 13, 5, 82, "Pb", 207.2, Colors.primaryChemistry, Colors.white) },
        { key: "Fl", value: new ChemicalElementModel("Flerovium", 13, 6, 114, "Fl", 289, Colors.primaryChemistry, Colors.white) },

        { key: "N", value: new ChemicalElementModel("Nitrogen", 14, 1, 7, "N", 14.0, Colors.primaryChemistry, Colors.white, true, false) },
        { key: "P", value: new ChemicalElementModel("Phosphorus", 14, 2, 15, "P", 31.0, Colors.primaryChemistry, Colors.white) },
        { key: "As", value: new ChemicalElementModel("Arsenic", 14, 3, 33, "As", 74.9, Colors.primaryChemistry, Colors.white) },
        { key: "Sb", value: new ChemicalElementModel("Antimony", 14, 4, 51, "Sb", 121.8, Colors.primaryChemistry, Colors.white) },
        { key: "Bi", value: new ChemicalElementModel("Bismuth", 14, 5, 83, "Bi", 209.0, Colors.primaryChemistry, Colors.white) },
        { key: "Mc", value: new ChemicalElementModel("Moscovium", 14, 6, 115, "Mc", 289, Colors.primaryChemistry, Colors.white) },

        { key: "O", value: new ChemicalElementModel("Oxygen", 15, 1, 8, "O", 16.0, Colors.primaryChemistry, Colors.white, true, false) },
        { key: "S", value: new ChemicalElementModel("Sulfur", 15, 2, 16, "S", 32.1, Colors.primaryChemistry, Colors.white) },
        { key: "Se", value: new ChemicalElementModel("Selenium", 15, 3, 34, "Se", 79.0, Colors.primaryChemistry, Colors.white) },
        { key: "Te", value: new ChemicalElementModel("Tellurium", 15, 4, 52, "Te", 127.6, Colors.primaryChemistry, Colors.white) },
        { key: "Po", value: new ChemicalElementModel("Polonium", 15, 5, 84, "Po", 210, Colors.primaryChemistry, Colors.white) },
        { key: "Lv", value: new ChemicalElementModel("Livermorium", 15, 6, 116, "Lv", 292, Colors.primaryChemistry, Colors.white) },

        { key: "F", value: new ChemicalElementModel("Fluorine", 16, 1, 9, "F", 19.0, Colors.primaryChemistry, Colors.white, true, false) },
        { key: "Cl", value: new ChemicalElementModel("Chlorine", 16, 2, 17, "Cl", 35.5, Colors.primaryChemistry, Colors.white) },
        { key: "Br", value: new ChemicalElementModel("Bromine", 16, 3, 35, "Br", 79.9, Colors.primaryChemistry, Colors.white) },
        { key: "I", value: new ChemicalElementModel("Iodine", 16, 4, 53, "I", 126.9, Colors.primaryChemistry, Colors.white) },
        { key: "At", value: new ChemicalElementModel("Astatine", 16, 5, 85, "At", 210, Colors.primaryChemistry, Colors.white) },
        { key: "Ts", value: new ChemicalElementModel("Tennessine", 16, 6, 117, "Ts", 294, Colors.primaryChemistry, Colors.white) },

        { key: "He", value: new ChemicalElementModel("Helium", 17, 0, 2, "He", 4.0, Colors.white, Colors.primaryChemistry, true, false) },
        { key: "Ne", value: new ChemicalElementModel("Neon", 17, 1, 10, "Ne", 20.2, Colors.primaryChemistry, Colors.white) },
        { key: "Ar", value: new ChemicalElementModel("Argon", 17, 2, 18, "Ar", 39.9, Colors.primaryChemistry, Colors.white) },
        { key: "Kr", value: new ChemicalElementModel("Krypton", 17, 3, 36, "Kr", 83.8, Colors.primaryChemistry, Colors.white) },
        { key: "Xe", value: new ChemicalElementModel("Xenon", 17, 4, 54, "Xe", 131.3, Colors.primaryChemistry, Colors.white) },
        { key: "Rn", value: new ChemicalElementModel("Radon", 17, 5, 86, "Rn", 222, Colors.primaryChemistry, Colors.white) },
        { key: "Og", value: new ChemicalElementModel("Oganesson", 17, 6, 118, "Og", 294, Colors.primaryChemistry, Colors.white) },

        //La
        { key: "Ce", value: new ChemicalElementModel("Cerium", 2, 7, 58, "Ce", 140.1, Colors.accent, Colors.white, false, false, "f Block") },
        { key: "Th", value: new ChemicalElementModel("Thorium", 2, 8, 90, "Th", 232.0, Colors.accent, Colors.white) },
        { key: "Pr", value: new ChemicalElementModel("Praseodymium", 3, 7, 59, "Pr", 140.9, Colors.accent, Colors.white) },
        { key: "Pa", value: new ChemicalElementModel("Protactinium", 3, 8, 91, "Pa", 231.0, Colors.accent, Colors.white) },
        { key: "Nd", value: new ChemicalElementModel("Neodymium", 4, 7, 60, "Nd", 144.2, Colors.accent, Colors.white) },
        { key: "U", value: new ChemicalElementModel("Uranium", 4, 8, 92, "U", 238.0, Colors.accent, Colors.white) },
        { key: "Pm", value: new ChemicalElementModel("Promethium", 5, 7, 61, "Pm", 145, Colors.accent, Colors.white) },
        { key: "Np", value: new ChemicalElementModel("Neptunium", 5, 8, 93, "Pu", 237, Colors.accent, Colors.white) },
        { key: "Sm", value: new ChemicalElementModel("Samarium", 6, 7, 62, "Sm", 150.4, Colors.accent, Colors.white) },
        { key: "Pu", value: new ChemicalElementModel("Plutonium", 6, 8, 94, "Pu", 244, Colors.accent, Colors.white) },
        { key: "Eu", value: new ChemicalElementModel("Europium", 7, 7, 63, "Eu", 152.0, Colors.accent, Colors.white) },
        { key: "Am", value: new ChemicalElementModel("Americium", 7, 8, 95, "Am", 243, Colors.accent, Colors.white) },
        { key: "Gd", value: new ChemicalElementModel("Gadolinium", 8, 7, 64, "Gd", 157.3, Colors.accent, Colors.white) },
        { key: "Cm", value: new ChemicalElementModel("Curium", 8, 8, 96, "Cm", 247, Colors.accent, Colors.white) },
        { key: "Tb", value: new ChemicalElementModel("Terbium", 9, 7, 65, "Tb", 158.9, Colors.accent, Colors.white) },
        { key: "Bk", value: new ChemicalElementModel("Berkelium", 9, 8, 97, "Bk", 247, Colors.accent, Colors.white) },
        { key: "Dy", value: new ChemicalElementModel("Dysprosium", 10, 7, 66, "Dy", 162.5, Colors.accent, Colors.white) },
        { key: "Cf", value: new ChemicalElementModel("Californium", 10, 8, 98, "Cf", 251, Colors.accent, Colors.white) },
        { key: "Ho", value: new ChemicalElementModel("Holmium", 11, 7, 67, "Ho", 164.9, Colors.accent, Colors.white) },
        { key: "Es", value: new ChemicalElementModel("Einseinium", 11, 8, 99, "Es", 252, Colors.accent, Colors.white) },
        { key: "Er", value: new ChemicalElementModel("Erbium", 12, 7, 68, "Er", 167.3, Colors.accent, Colors.white) },
        { key: "Fm", value: new ChemicalElementModel("Fermium", 12, 8, 100, "Fm", 257, Colors.accent, Colors.white) },
        { key: "Tm", value: new ChemicalElementModel("Thulium", 13, 7, 69, "Tm", 168.9, Colors.accent, Colors.white) },
        { key: "Md", value: new ChemicalElementModel("Mendelevium", 13, 8, 101, "Md", 258, Colors.accent, Colors.white) },
        { key: "Yb", value: new ChemicalElementModel("Ytterbium", 14, 7, 70, "Yb", 173.1, Colors.accent, Colors.white) },
        { key: "No", value: new ChemicalElementModel("Nobelium", 14, 8, 102, "No", 259, Colors.accent, Colors.white) },
        { key: "Lu", value: new ChemicalElementModel("Lutenium", 15, 7, 71, "Lu", 175.0, Colors.accent, Colors.white) },
        { key: "Lr", value: new ChemicalElementModel("Lawrencium", 15, 8, 103, "Lr", 262, Colors.accent, Colors.white) },
    ]
}