// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BiobrainWebContext))]
    [Migration("20220426104510_UserPromoCodeConfiguration")]
    partial class UserPromoCodeConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Biobrain.Domain.Entities.Content.ContentTreeEntity", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTreeMetaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("IconId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("NodeId");

                    b.HasIndex("ContentTreeMetaId");

                    b.HasIndex("CourseId");

                    b.HasIndex("IconId");

                    b.HasIndex("ParentId");

                    b.ToTable("ContentTree");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Content.ContentVersionEntity", b =>
                {
                    b.Property<Guid>("ContentVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentFileName")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ContentVersionId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.HasIndex("Version");

                    b.ToTable("ContentVersion");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Content.IconEntity", b =>
                {
                    b.Property<Guid>("IconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("IconId");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Course.CourseEntity", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurriculumCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsForSell")
                        .HasColumnType("boolean");

                    b.Property<int>("SubjectCode")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("CourseId");

                    b.HasIndex("CurriculumCode");

                    b.HasIndex("SubjectCode", "CurriculumCode", "Year")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Course.CurriculumEntity", b =>
                {
                    b.Property<int>("CurriculumCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CurriculumCode");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Curricula");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Course.SubjectEntity", b =>
                {
                    b.Property<int>("SubjectCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("SubjectCode");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Glossary.TermEntity", b =>
                {
                    b.Property<Guid>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<int>("SubjectCode")
                        .HasColumnType("integer");

                    b.Property<string>("Term")
                        .HasColumnType("text");

                    b.HasKey("TermId");

                    b.HasIndex("SubjectCode");

                    b.ToTable("GlossaryTerms");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.BookmarkEntity", b =>
                {
                    b.Property<Guid>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BookmarkId");

                    b.HasIndex("CourseId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.MaterialEntity", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.PageEntity", b =>
                {
                    b.Property<Guid>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTreeId")
                        .HasColumnType("uuid");

                    b.HasKey("PageId");

                    b.HasIndex("ContentTreeId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.PageMaterialEntity", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("PageId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("PageMaterials");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.MaterialAssignments.LearningMaterialAssignmentEntity", b =>
                {
                    b.Property<Guid>("LearningMaterialAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTreeNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsForWholeClass")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SchoolClassId")
                        .HasColumnType("uuid");

                    b.HasKey("LearningMaterialAssignmentId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("ContentTreeNodeId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("LearningMaterialAssignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.MaterialAssignments.LearningMaterialUserAssignmentEntity", b =>
                {
                    b.Property<Guid>("LearningMaterialUserAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DueAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LearningMaterialAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LearningMaterialUserAssignmentId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("LearningMaterialAssignmentId");

                    b.ToTable("LearningMaterialUserAssignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Notifications.EmailMessageEntity", b =>
                {
                    b.Property<Guid>("EmailMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("EmailMessageId");

                    b.ToTable("EmailMessageQueue");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.LastPaidScheduledPaymentEntity", b =>
                {
                    b.Property<Guid>("LastPaidScheduledPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ScheduledPaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LastPaidScheduledPaymentId");

                    b.HasIndex("ScheduledPaymentId");

                    b.ToTable("LastPaidScheduledPayment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.LastPaymentReviewEntity", b =>
                {
                    b.Property<Guid>("LastPaymentReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PayDate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LastPaymentReviewId");

                    b.ToTable("LastPaymentReview");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.PaymentEntity", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Amount")
                        .HasColumnType("text");

                    b.Property<string>("ChargeRefId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FailedPayload")
                        .HasColumnType("text");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("ScheduledPaymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransferRefId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PaymentId");

                    b.HasIndex("ScheduledPaymentId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.PromoCodeEntity", b =>
                {
                    b.Property<Guid>("PromoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int?>("BundleSize")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PaymentPeriod")
                        .HasColumnType("integer");

                    b.Property<double?>("Percent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PromoCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.ScheduledPaymentCourseEntity", b =>
                {
                    b.Property<Guid>("ScheduledPaymentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduledPaymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ScheduledPaymentCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ScheduledPaymentId");

                    b.ToTable("ScheduledPaymentCourse");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.ScheduledPaymentEntity", b =>
                {
                    b.Property<Guid>("ScheduledPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LeapPayDate")
                        .HasColumnType("integer");

                    b.Property<int>("PayDate")
                        .HasColumnType("integer");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduledPaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledPayment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.UserPaymentDetailsEntity", b =>
                {
                    b.Property<Guid>("UserPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PinPaymentCustomerRefId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPaymentDetails");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.UserPromoCodeEntity", b =>
                {
                    b.Property<Guid>("UserPromoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPromoCodeId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPromoCodes");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Question.QuestionEntity", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FeedBack")
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<string>("Hint")
                        .HasColumnType("text");

                    b.Property<long>("QuestionTypeCode")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionTypeCode");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Question.QuestionTypeEntity", b =>
                {
                    b.Property<long>("QuestionTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsInUse")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("QuestionTypeCode");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Question.QuizQuestionEntity", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId", "QuizId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizAssignmentEntity", b =>
                {
                    b.Property<Guid>("QuizAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AssignedByTeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DueAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchoolClassId")
                        .HasColumnType("uuid");

                    b.HasKey("QuizAssignmentId");

                    b.HasIndex("AssignedByTeacherId");

                    b.HasIndex("QuizId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("QuizAssignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizEntity", b =>
                {
                    b.Property<Guid>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTreeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("QuizId");

                    b.HasIndex("ContentTreeId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizResultEntity", b =>
                {
                    b.Property<Guid>("QuizStudentAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StaredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("QuizStudentAssignmentId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizResultQuestionEntity", b =>
                {
                    b.Property<Guid>("QuizResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("QuizResultId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizResultQuestions");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizStreakEntity", b =>
                {
                    b.Property<Guid>("QuizStreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DaysCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("WeeksStreak")
                        .HasColumnType("integer");

                    b.HasKey("QuizStreakId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizStreak");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizStudentAssignmentEntity", b =>
                {
                    b.Property<Guid>("QuizStudentAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DueAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("QuizAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("QuizStudentAssignmentId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("QuizAssignmentId");

                    b.ToTable("QuizStudentAssignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolAdminEntity", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("SchoolId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SchoolAdmins");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolEntity", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsLicensesNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TeachersLicensesNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SchoolId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolStudentEntity", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SchoolId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SchoolStudents");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolTeacherEntity", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SchoolId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SchoolTeachers");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", b =>
                {
                    b.Property<Guid>("SchoolClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutoJoinClassCode")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("SchoolClassId");

                    b.HasIndex("AutoJoinClassCode")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("SchoolId", "Year", "Name")
                        .IsUnique();

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassStudentEntity", b =>
                {
                    b.Property<Guid>("SchoolClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SchoolClassId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SchoolClassStudents");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassTeacherEntity", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TeacherId", "SchoolClassId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("SchoolClassTeachers");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.RoleClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserLoginEntity", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserTokenEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Student.StudentEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CurriculumCode")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("CurriculumCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Teacher.TeacherEntity", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Templates.CourseTemplateEntity", b =>
                {
                    b.Property<Guid>("CourseTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("CourseTemplateId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TemplateId");

                    b.ToTable("CourseTemplates");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Templates.TemplateEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("TemplateId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("DataAccessLayer.WebAppEntities.AnswerEntity", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswerOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Response")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("DataAccessLayer.WebAppEntities.ContentTreeMetaEntity", b =>
                {
                    b.Property<Guid>("ContentTreeMetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoExpand")
                        .HasColumnType("boolean");

                    b.Property<bool>("CouldAddContent")
                        .HasColumnType("boolean");

                    b.Property<bool>("CouldAddEntry")
                        .HasColumnType("boolean");

                    b.Property<bool>("CouldCopyIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Depth")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("StartIndex")
                        .HasColumnType("integer");

                    b.HasKey("ContentTreeMetaId");

                    b.ToTable("ContentTreeMeta");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Content.ContentTreeEntity", b =>
                {
                    b.HasOne("DataAccessLayer.WebAppEntities.ContentTreeMetaEntity", "ContentTreeMeta")
                        .WithMany()
                        .HasForeignKey("ContentTreeMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Content.IconEntity", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.HasOne("Biobrain.Domain.Entities.Content.ContentTreeEntity", "ParentContentTree")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("ContentTreeMeta");

                    b.Navigation("Course");

                    b.Navigation("Icon");

                    b.Navigation("ParentContentTree");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Content.ContentVersionEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithOne("Version")
                        .HasForeignKey("Biobrain.Domain.Entities.Content.ContentVersionEntity", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Course.CourseEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CurriculumEntity", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Course.SubjectEntity", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Glossary.TermEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.SubjectEntity", "Subject")
                        .WithMany("Glossary")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.BookmarkEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Material.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.PageEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Content.ContentTreeEntity", "ContentTreeNode")
                        .WithMany()
                        .HasForeignKey("ContentTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentTreeNode");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.PageMaterialEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Material.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Material.PageEntity", "Page")
                        .WithMany("PageMaterials")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.MaterialAssignments.LearningMaterialAssignmentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "AssignedBy")
                        .WithMany("AssignedByUserMaterials")
                        .HasForeignKey("AssignedByUserId");

                    b.HasOne("Biobrain.Domain.Entities.Content.ContentTreeEntity", "ContentTreeNode")
                        .WithMany("Assignments")
                        .HasForeignKey("ContentTreeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", "SchoolClass")
                        .WithMany("AssignedMaterials")
                        .HasForeignKey("SchoolClassId");

                    b.Navigation("AssignedBy");

                    b.Navigation("ContentTreeNode");

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.MaterialAssignments.LearningMaterialUserAssignmentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "AssignedTo")
                        .WithMany("AssignedMaterials")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.MaterialAssignments.LearningMaterialAssignmentEntity", "LearningMaterialAssignment")
                        .WithMany("UserAssignments")
                        .HasForeignKey("LearningMaterialAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("LearningMaterialAssignment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.LastPaidScheduledPaymentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Payment.ScheduledPaymentEntity", "ScheduledPayment")
                        .WithMany()
                        .HasForeignKey("ScheduledPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledPayment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.PaymentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Payment.ScheduledPaymentEntity", "ScheduledPayment")
                        .WithMany()
                        .HasForeignKey("ScheduledPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledPayment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.ScheduledPaymentCourseEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Payment.ScheduledPaymentEntity", "ScheduledPayment")
                        .WithMany("ScheduledPaymentCourses")
                        .HasForeignKey("ScheduledPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("ScheduledPayment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.ScheduledPaymentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "User")
                        .WithMany("ScheduledPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.UserPaymentDetailsEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "User")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.UserPromoCodeEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Payment.PromoCodeEntity", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Question.QuestionEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Question.QuestionTypeEntity", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Question.QuizQuestionEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Question.QuestionEntity", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Quiz.QuizEntity", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizAssignmentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Teacher.TeacherEntity", "AssignedBy")
                        .WithMany("AssignedByTeacherQuizzes")
                        .HasForeignKey("AssignedByTeacherId");

                    b.HasOne("Biobrain.Domain.Entities.Quiz.QuizEntity", "Quiz")
                        .WithMany("Assignments")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", "SchoolClass")
                        .WithMany("AssignedQuizzes")
                        .HasForeignKey("SchoolClassId");

                    b.Navigation("AssignedBy");

                    b.Navigation("Quiz");

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Content.ContentTreeEntity", "ContentTreeNode")
                        .WithMany()
                        .HasForeignKey("ContentTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentTreeNode");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizResultEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Quiz.QuizStudentAssignmentEntity", "QuizStudentAssignment")
                        .WithOne("Result")
                        .HasForeignKey("Biobrain.Domain.Entities.Quiz.QuizResultEntity", "QuizStudentAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizStudentAssignment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizResultQuestionEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Question.QuestionEntity", "Question")
                        .WithMany("QuizResultQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Quiz.QuizResultEntity", "QuizResult")
                        .WithMany("Questions")
                        .HasForeignKey("QuizResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizStreakEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Student.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizStudentAssignmentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "AssignedTo")
                        .WithMany("AssignedQuizzes")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Quiz.QuizAssignmentEntity", "QuizAssignment")
                        .WithMany("QuizStudentAssignments")
                        .HasForeignKey("QuizAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("QuizAssignment");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolAdminEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.School.SchoolEntity", "School")
                        .WithMany("SchoolAdmins")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Teacher.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolStudentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.School.SchoolEntity", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Student.StudentEntity", "Student")
                        .WithMany("Schools")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolTeacherEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.School.SchoolEntity", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Teacher.TeacherEntity", "Teacher")
                        .WithMany("Schools")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.School.SchoolEntity", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassStudentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", "SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Student.StudentEntity", "Student")
                        .WithMany("SchoolClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassTeacherEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", "SchoolClass")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Teacher.TeacherEntity", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.RoleClaimEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserClaimEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserLoginEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserRoleEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserTokenEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Student.StudentEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CurriculumEntity", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumCode");

                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "User")
                        .WithOne("Student")
                        .HasForeignKey("Biobrain.Domain.Entities.Student.StudentEntity", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Teacher.TeacherEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.SiteIdentity.UserEntity", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("Biobrain.Domain.Entities.Teacher.TeacherEntity", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Templates.CourseTemplateEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Course.CourseEntity", "Course")
                        .WithMany("Templates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobrain.Domain.Entities.Templates.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DataAccessLayer.WebAppEntities.AnswerEntity", b =>
                {
                    b.HasOne("Biobrain.Domain.Entities.Question.QuestionEntity", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Content.ContentTreeEntity", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Course.CourseEntity", b =>
                {
                    b.Navigation("Templates");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Course.SubjectEntity", b =>
                {
                    b.Navigation("Glossary");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Material.PageEntity", b =>
                {
                    b.Navigation("PageMaterials");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.MaterialAssignments.LearningMaterialAssignmentEntity", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Payment.ScheduledPaymentEntity", b =>
                {
                    b.Navigation("ScheduledPaymentCourses");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Question.QuestionEntity", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuizQuestions");

                    b.Navigation("QuizResultQuestions");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizAssignmentEntity", b =>
                {
                    b.Navigation("QuizStudentAssignments");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizResultEntity", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Quiz.QuizStudentAssignmentEntity", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.School.SchoolEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("SchoolAdmins");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SchoolClass.SchoolClassEntity", b =>
                {
                    b.Navigation("AssignedMaterials");

                    b.Navigation("AssignedQuizzes");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.SiteIdentity.UserEntity", b =>
                {
                    b.Navigation("AssignedByUserMaterials");

                    b.Navigation("AssignedMaterials");

                    b.Navigation("AssignedQuizzes");

                    b.Navigation("PaymentDetails");

                    b.Navigation("ScheduledPayments");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Student.StudentEntity", b =>
                {
                    b.Navigation("SchoolClasses");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("Biobrain.Domain.Entities.Teacher.TeacherEntity", b =>
                {
                    b.Navigation("AssignedByTeacherQuizzes");

                    b.Navigation("Classes");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
