//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT BIOBRAIN PHYSICS.
        /// </summary>
        public static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUTORIAL.
        /// </summary>
        public static string AboutViewHeaderString {
            get {
                return ResourceManager.GetString("AboutViewHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted.
        /// </summary>
        public static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BioBrain Account and all its data has been deleted..
        /// </summary>
        public static string AccountDeletedDescription {
            get {
                return ResourceManager.GetString("AccountDeletedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add email.
        /// </summary>
        public static string AddEmailString {
            get {
                return ResourceManager.GetString("AddEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Content Package.
        /// </summary>
        public static string AllContentPackageString {
            get {
                return ResourceManager.GetString("AllContentPackageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is already owned..
        /// </summary>
        public static string AlreadyOwnedError {
            get {
                return ResourceManager.GetString("AlreadyOwnedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already purchased the full version, but for some reason have not downloaded full content. Download?.
        /// </summary>
        public static string AlreadyPurchasedMessage {
            get {
                return ResourceManager.GetString("AlreadyPurchasedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string ApplyString {
            get {
                return ResourceManager.GetString("ApplyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biobrain - Physics.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Store.
        /// </summary>
        public static string AppStore {
            get {
                return ResourceManager.GetString("AppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to upgrade the app to latest version to receive updates..
        /// </summary>
        public static string AppUpdateNeedString {
            get {
                return ResourceManager.GetString("AppUpdateNeedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application vesrsion.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application version is to low. Please, update the application..
        /// </summary>
        public static string AppVersionError {
            get {
                return ResourceManager.GetString("AppVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREAS OF STUDY.
        /// </summary>
        public static string AreasOfStudyString {
            get {
                return ResourceManager.GetString("AreasOfStudyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a subscriber?.
        /// </summary>
        public static string AreYouSubscriber {
            get {
                return ResourceManager.GetString("AreYouSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Mass.
        /// </summary>
        public static string AtomicMassString {
            get {
                return ResourceManager.GetString("AtomicMassString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic.
        /// </summary>
        public static string AtomicString {
            get {
                return ResourceManager.GetString("AtomicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string AuthorizationString {
            get {
                return ResourceManager.GetString("AuthorizationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average quiz score.
        /// </summary>
        public static string AverageQuizScoreString {
            get {
                return ResourceManager.GetString("AverageQuizScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string AverageString {
            get {
                return ResourceManager.GetString("AverageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CancelUpperString {
            get {
                return ResourceManager.GetString("CancelUpperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving an update. Please contact support..
        /// </summary>
        public static string CheckForUpdatesError {
            get {
                return ResourceManager.GetString("CheckForUpdatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string CheckingForUpdatesString {
            get {
                return ResourceManager.GetString("CheckingForUpdatesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click download button below to start.
        /// </summary>
        public static string ClickDownloadString {
            get {
                return ResourceManager.GetString("ClickDownloadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This level is coming soon.
        /// </summary>
        public static string ComingSoonLevel {
            get {
                return ResourceManager.GetString("ComingSoonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon....
        /// </summary>
        public static string ComingSoonString {
            get {
                return ResourceManager.GetString("ComingSoonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string CompletedString {
            get {
                return ResourceManager.GetString("CompletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password should be the same.
        /// </summary>
        public static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPasswordString {
            get {
                return ResourceManager.GetString("ConfirmPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Account Deletion.
        /// </summary>
        public static string ContinueAccountDeletion {
            get {
                return ResourceManager.GetString("ContinueAccountDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer:.
        /// </summary>
        public static string CorrectString {
            get {
                return ResourceManager.GetString("CorrectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryString {
            get {
                return ResourceManager.GetString("CountryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccountString {
            get {
                return ResourceManager.GetString("CreateAccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ACCOUNT.
        /// </summary>
        public static string CreateAccountUpperString {
            get {
                return ResourceManager.GetString("CreateAccountUpperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string DataSyncString {
            get {
                return ResourceManager.GetString("DataSyncString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date completed.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirthString {
            get {
                return ResourceManager.GetString("DateOfBirthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DatePrefix {
            get {
                return ResourceManager.GetString("DatePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string DateString {
            get {
                return ResourceManager.GetString("DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d Block.
        /// </summary>
        public static string DBlockString {
            get {
                return ResourceManager.GetString("DBlockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.html.
        /// </summary>
        public static string DefaultPage {
            get {
                return ResourceManager.GetString("DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you delete your BioBrain account, you won’t be able to retrieve the learning material, the glossary or quizzes. All your results will also be deleted..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you press the button below, your account will be deleted, until you subscribe again. Thank you for using BioBrain..
        /// </summary>
        public static string DeleteAccountLastDescription {
            get {
                return ResourceManager.GetString("DeleteAccountLastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE MY ACCOUNT.
        /// </summary>
        public static string DeleteMyAccount {
            get {
                return ResourceManager.GetString("DeleteMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting your account is permanent..
        /// </summary>
        public static string DeletingAccountPermanent {
            get {
                return ResourceManager.GetString("DeletingAccountPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneString {
            get {
                return ResourceManager.GetString("DoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading content.
        /// </summary>
        public static string DownloadingContentString {
            get {
                return ResourceManager.GetString("DownloadingContentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DownloadingString {
            get {
                return ResourceManager.GetString("DownloadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadString {
            get {
                return ResourceManager.GetString("DownloadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like the app?.
        /// </summary>
        public static string DoYouLikeString {
            get {
                return ResourceManager.GetString("DoYouLikeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What level are you currently studying?.
        /// </summary>
        public static string EducationLevelString {
            get {
                return ResourceManager.GetString("EducationLevelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailString {
            get {
                return ResourceManager.GetString("EmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs are empty!.
        /// </summary>
        public static string EmptyLogsError {
            get {
                return ResourceManager.GetString("EmptyLogsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY PROMO CODE.
        /// </summary>
        public static string EnterPromoCodeString {
            get {
                return ResourceManager.GetString("EnterPromoCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f Block.
        /// </summary>
        public static string FBlockString {
            get {
                return ResourceManager.GetString("FBlockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        public static string FeedbackString {
            get {
                return ResourceManager.GetString("FeedbackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Biobrain..
        /// </summary>
        public static string FeedbackThankString {
            get {
                return ResourceManager.GetString("FeedbackThankString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files failed to download.
        /// </summary>
        public static string FilesFailedString {
            get {
                return ResourceManager.GetString("FilesFailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameString {
            get {
                return ResourceManager.GetString("FirstNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;p class=&quot;correctString&quot;&gt;Incorrect.&lt;/p&gt;&lt;p&gt;Please try again.&lt;/p&gt;{0}&lt;/html&gt;.
        /// </summary>
        public static string FirstTryString {
            get {
                return ResourceManager.GetString("FirstTryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPasswordString {
            get {
                return ResourceManager.GetString("ForgotPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% complete.
        /// </summary>
        public static string FullCompleteString {
            get {
                return ResourceManager.GetString("FullCompleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderString {
            get {
                return ResourceManager.GetString("GenderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to get account data from remote server..
        /// </summary>
        public static string GetAccountError {
            get {
                return ResourceManager.GetString("GetAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy full content.
        /// </summary>
        public static string GetFullString {
            get {
                return ResourceManager.GetString("GetFullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pay {0} to access full content. If you had bought Biobrain Biology earlier, please provide your email..
        /// </summary>
        public static string GetFullVersionOrAuthorizeString {
            get {
                return ResourceManager.GetString("GetFullVersionOrAuthorizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pay {0} to access full content..
        /// </summary>
        public static string GetFullVersionString {
            get {
                return ResourceManager.GetString("GetFullVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get product info..
        /// </summary>
        public static string GetPriceErrorString {
            get {
                return ResourceManager.GetString("GetPriceErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        public static string GiveFeedbackString {
            get {
                return ResourceManager.GetString("GiveFeedbackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOSSARY.
        /// </summary>
        public static string GlossaryString {
            get {
                return ResourceManager.GetString("GlossaryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOODBYE.
        /// </summary>
        public static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Play.
        /// </summary>
        public static string GooglePlay {
            get {
                return ResourceManager.GetString("GooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsString {
            get {
                return ResourceManager.GetString("GroupsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;correctString&quot;&gt;HINT:&lt;/p&gt;.
        /// </summary>
        public static string HintHeader {
            get {
                return ResourceManager.GetString("HintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span&gt;Tap &lt;img src=&quot;Icons/LightGlobeIcon.png&quot; height=&quot;40px&quot; width=&quot;40px&quot; style=&quot;vertical-align: middle&quot;/&gt; for a hint.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string HintTextForWrongAnswer {
            get {
                return ResourceManager.GetString("HintTextForWrongAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        public static string HistoryHeaderString {
            get {
                return ResourceManager.GetString("HistoryHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:/sdcard/Download/Icons/.
        /// </summary>
        public static string IconsPath {
            get {
                return ResourceManager.GetString("IconsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not found.
        /// </summary>
        public static string InvalidEmailError {
            get {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPasswordError {
            get {
                return ResourceManager.GetString("InvalidEmailOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPasswordError {
            get {
                return ResourceManager.GetString("InvalidPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product..
        /// </summary>
        public static string InvalidProductError {
            get {
                return ResourceManager.GetString("InvalidProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEAVE A REVIEW.
        /// </summary>
        public static string LeaveAReviewString {
            get {
                return ResourceManager.GetString("LeaveAReviewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry to see you go! We’d love to know why you want to delete your account, so we can improve the app and support our community.
        /// </summary>
        public static string LeavingDescription {
            get {
                return ResourceManager.GetString("LeavingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string LevelPrefix {
            get {
                return ResourceManager.GetString("LevelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I LIKE THE APP.
        /// </summary>
        public static string LikeString {
            get {
                return ResourceManager.GetString("LikeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biobrain Physics.
        /// </summary>
        public static string LiteVersionHeader {
            get {
                return ResourceManager.GetString("LiteVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingLabelString {
            get {
                return ResourceManager.GetString("LoadingLabelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginString {
            get {
                return ResourceManager.GetString("LoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LoginUpperString {
            get {
                return ResourceManager.GetString("LoginUpperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs have been successfully sent.
        /// </summary>
        public static string LogsSendedMessage {
            get {
                return ResourceManager.GetString("LogsSendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogsString {
            get {
                return ResourceManager.GetString("LogsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you love Biobrain?.
        /// </summary>
        public static string LoveBiobrainString {
            get {
                return ResourceManager.GetString("LoveBiobrainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string ManString {
            get {
                return ResourceManager.GetString("ManString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYBE LATER.
        /// </summary>
        public static string MaybeLaterString {
            get {
                return ResourceManager.GetString("MaybeLaterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My.
        /// </summary>
        public static string My {
            get {
                return ResourceManager.GetString("My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to.
        /// </summary>
        public static string NavigateToString {
            get {
                return ResourceManager.GetString("NavigateToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content update is available. Download?.
        /// </summary>
        public static string NeedUpdateMessage {
            get {
                return ResourceManager.GetString("NeedUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        public static string NewVersionAvailableString {
            get {
                return ResourceManager.GetString("NewVersionAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT LEVEL.
        /// </summary>
        public static string NextLevelString {
            get {
                return ResourceManager.GetString("NextLevelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT TOPIC.
        /// </summary>
        public static string NextTopicString {
            get {
                return ResourceManager.GetString("NextTopicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the server. Please check your internet connection..
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        public static string NoInternetError {
            get {
                return ResourceManager.GetString("NoInternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions to follow..
        /// </summary>
        public static string NoQuestionString {
            get {
                return ResourceManager.GetString("NoQuestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoString {
            get {
                return ResourceManager.GetString("NoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the app store. Please check your internet connection..
        /// </summary>
        public static string NotConnectedException {
            get {
                return ResourceManager.GetString("NotConnectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am not currently studying.
        /// </summary>
        public static string NotStudingString {
            get {
                return ResourceManager.GetString("NotStudingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        public static string NoUpdatesAvailableString {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberString {
            get {
                return ResourceManager.GetString("NumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string OrString {
            get {
                return ResourceManager.GetString("OrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherString {
            get {
                return ResourceManager.GetString("OtherString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///sdcard/Download/.
        /// </summary>
        public static string PagesPath {
            get {
                return ResourceManager.GetString("PagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment..
        /// </summary>
        public static string PaymentInvalidError {
            get {
                return ResourceManager.GetString("PaymentInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment not alowed..
        /// </summary>
        public static string PaymentNotAllowedError {
            get {
                return ResourceManager.GetString("PaymentNotAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT POLICY.
        /// </summary>
        public static string PaymentPolicyString {
            get {
                return ResourceManager.GetString("PaymentPolicyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p Block.
        /// </summary>
        public static string PBlockString {
            get {
                return ResourceManager.GetString("PBlockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic table.
        /// </summary>
        public static string PeriodicTableString {
            get {
                return ResourceManager.GetString("PeriodicTableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string PeriodsString {
            get {
                return ResourceManager.GetString("PeriodsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string PrimaryString {
            get {
                return ResourceManager.GetString("PrimaryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVACY POLICY.
        /// </summary>
        public static string PrivacyPolicyString {
            get {
                return ResourceManager.GetString("PrivacyPolicyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE&apos;S A PROBLEM.
        /// </summary>
        public static string ProblemPolicyString {
            get {
                return ResourceManager.GetString("ProblemPolicyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I%20have%20a%20problem%20with%20Biobrain.
        /// </summary>
        public static string ProblemSubjectString {
            get {
                return ResourceManager.GetString("ProblemSubjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid promo code..
        /// </summary>
        public static string PromoCodeError {
            get {
                return ResourceManager.GetString("PromoCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        public static string PromoCodeString {
            get {
                return ResourceManager.GetString("PromoCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide email.
        /// </summary>
        public static string ProvideEmailString {
            get {
                return ResourceManager.GetString("ProvideEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make purchase..
        /// </summary>
        public static string PurchaseError {
            get {
                return ResourceManager.GetString("PurchaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASES.
        /// </summary>
        public static string PurchasesString {
            get {
                return ResourceManager.GetString("PurchasesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string PurchaseString {
            get {
                return ResourceManager.GetString("PurchaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the question to review.
        /// </summary>
        public static string QuestionReviewNoteString {
            get {
                return ResourceManager.GetString("QuestionReviewNoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QuestionString {
            get {
                return ResourceManager.GetString("QuestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizzes.
        /// </summary>
        public static string QuizesString {
            get {
                return ResourceManager.GetString("QuizesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quiz score.
        /// </summary>
        public static string QuizScoreString {
            get {
                return ResourceManager.GetString("QuizScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizes completed.
        /// </summary>
        public static string QuizzesCompletedString {
            get {
                return ResourceManager.GetString("QuizzesCompletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE THE APP.
        /// </summary>
        public static string RateTheAppString {
            get {
                return ResourceManager.GetString("RateTheAppString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is not what I am after.
        /// </summary>
        public static string ReasonBadContent {
            get {
                return ResourceManager.GetString("ReasonBadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is not relevant.
        /// </summary>
        public static string ReasonContentNotRelevant {
            get {
                return ResourceManager.GetString("ReasonContentNotRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have finished studying my course.
        /// </summary>
        public static string ReasonFinishCourse {
            get {
                return ResourceManager.GetString("ReasonFinishCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ReasonOther {
            get {
                return ResourceManager.GetString("ReasonOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is too hard.
        /// </summary>
        public static string ReasonTooHard {
            get {
                return ResourceManager.GetString("ReasonTooHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT QUIZZES.
        /// </summary>
        public static string RecentQuizzesString {
            get {
                return ResourceManager.GetString("RecentQuizzesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION SCREEN.
        /// </summary>
        public static string RegistrationScreenString {
            get {
                return ResourceManager.GetString("RegistrationScreenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEAT.
        /// </summary>
        public static string RepeatString {
            get {
                return ResourceManager.GetString("RepeatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required.
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with password reset instructions was sent to the email address.
        /// </summary>
        public static string ResetEmailSentString {
            get {
                return ResourceManager.GetString("ResetEmailSentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biobrain - Physics Result.
        /// </summary>
        public static string ResultEmailSubject {
            get {
                return ResourceManager.GetString("ResultEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTS.
        /// </summary>
        public static string ResultHeaderString {
            get {
                return ResourceManager.GetString("ResultHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string ResultsString {
            get {
                return ResourceManager.GetString("ResultsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETAKE QUIZ.
        /// </summary>
        public static string RetakeQuiz {
            get {
                return ResourceManager.GetString("RetakeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake quiz.
        /// </summary>
        public static string RetakeQuizString {
            get {
                return ResourceManager.GetString("RetakeQuizString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Please leave us.
        /// </summary>
        public static string Review1String {
            get {
                return ResourceManager.GetString("Review1String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a review in the Google Play..
        /// </summary>
        public static string Review2DroidString {
            get {
                return ResourceManager.GetString("Review2DroidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a review in the App Store..
        /// </summary>
        public static string Review2IOSString {
            get {
                return ResourceManager.GetString("Review2IOSString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SaveString {
            get {
                return ResourceManager.GetString("SaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Save 50%, 12 months at {0}/mo).
        /// </summary>
        public static string SaveSubscriptionString {
            get {
                return ResourceManager.GetString("SaveSubscriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s Block.
        /// </summary>
        public static string SBlockString {
            get {
                return ResourceManager.GetString("SBlockString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        public static string ScorePrefix {
            get {
                return ResourceManager.GetString("ScorePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCORE.
        /// </summary>
        public static string ScoreString {
            get {
                return ResourceManager.GetString("ScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        public static string SearchPlaceholderString {
            get {
                return ResourceManager.GetString("SearchPlaceholderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string SecondaryString {
            get {
                return ResourceManager.GetString("SecondaryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;p class=&quot;correctString&quot;&gt;Incorrect response.&lt;/p&gt;&lt;p&gt;Correct answer is {0}&lt;/p&gt;&lt;p&gt;{1}&lt;/p&gt;&lt;/html&gt;.
        /// </summary>
        public static string SecondTryString {
            get {
                return ResourceManager.GetString("SecondTryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A LEVEL.
        /// </summary>
        public static string SelectALevelString {
            get {
                return ResourceManager.GetString("SelectALevelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To receive updates you need to specify your email..
        /// </summary>
        public static string SelectEmailString {
            get {
                return ResourceManager.GetString("SelectEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send logs! Please contact us via email: support@biobrain.com.au.
        /// </summary>
        public static string SendLogError {
            get {
                return ResourceManager.GetString("SendLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND LOG.
        /// </summary>
        public static string SendLogString {
            get {
                return ResourceManager.GetString("SendLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET PASSWORD.
        /// </summary>
        public static string SendResetPasswordString {
            get {
                return ResourceManager.GetString("SendResetPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendString {
            get {
                return ResourceManager.GetString("SendString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW MORE RESULTS.
        /// </summary>
        public static string ShowMoreString {
            get {
                return ResourceManager.GetString("ShowMoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateString {
            get {
                return ResourceManager.GetString("StateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz results.
        /// </summary>
        public static string StatsHeaderString {
            get {
                return ResourceManager.GetString("StatsHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz results summary.
        /// </summary>
        public static string StatsSummaryHeaderString {
            get {
                return ResourceManager.GetString("StatsSummaryHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t store version. Please contact us .
        /// </summary>
        public static string StoreVersionError {
            get {
                return ResourceManager.GetString("StoreVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDY.
        /// </summary>
        public static string Study {
            get {
                return ResourceManager.GetString("Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICS REGISTRATION.
        /// </summary>
        public static string SubjectRegistrationString {
            get {
                return ResourceManager.GetString("SubjectRegistrationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICS.
        /// </summary>
        public static string SubjectString {
            get {
                return ResourceManager.GetString("SubjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take into account that billing will continue through Apple. Please cancel your subscription before continuing..
        /// </summary>
        public static string SubscriberDescription {
            get {
                return ResourceManager.GetString("SubscriberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS RATE.
        /// </summary>
        public static string SuccessRateString {
            get {
                return ResourceManager.GetString("SuccessRateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGESTIONS.
        /// </summary>
        public static string SuggestionString {
            get {
                return ResourceManager.GetString("SuggestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions%20for%20Biobrain.
        /// </summary>
        public static string SuggestionSubjectString {
            get {
                return ResourceManager.GetString("SuggestionSubjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SurnameString {
            get {
                return ResourceManager.GetString("SurnameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SymbolString {
            get {
                return ResourceManager.GetString("SymbolString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take quiz.
        /// </summary>
        public static string TakeQuizString {
            get {
                return ResourceManager.GetString("TakeQuizString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS OF SERVICE.
        /// </summary>
        public static string TermsOfServiceString {
            get {
                return ResourceManager.GetString("TermsOfServiceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary.
        /// </summary>
        public static string TertiaryString {
            get {
                return ResourceManager.GetString("TertiaryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I%20recommend%20you%20try%20out%20Biobrain%2C%20a%20Biology%20learning%20app.%0AAvailable%20in%20the%20AppStore%20and%20Google%20Play%20Store.%0Awww.biobrain.com.au.
        /// </summary>
        public static string TextToShare {
            get {
                return ResourceManager.GetString("TextToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attempts. Please try again later..
        /// </summary>
        public static string TooManyAttemptsError {
            get {
                return ResourceManager.GetString("TooManyAttemptsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPIC.
        /// </summary>
        public static string TopicString {
            get {
                return ResourceManager.GetString("TopicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during authentication. Try the following steps:
        ///1. Delete the app
        ///2. Install the app from the App Store
        ///3. Create an account by completing the registration page.
        /// </summary>
        public static string UnhandledLoginError {
            get {
                return ResourceManager.GetString("UnhandledLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string UnspecifiedString {
            get {
                return ResourceManager.GetString("UnspecifiedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to update account data on remote server..
        /// </summary>
        public static string UpdateAccountError {
            get {
                return ResourceManager.GetString("UpdateAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading an update. Please try again later..
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string UpdatesString {
            get {
                return ResourceManager.GetString("UpdatesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateString {
            get {
                return ResourceManager.GetString("UpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string UpgradeString {
            get {
                return ResourceManager.GetString("UpgradeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists.
        /// </summary>
        public static string UsedEmailError {
            get {
                return ResourceManager.GetString("UsedEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase was canceled by user..
        /// </summary>
        public static string UserCanceledError {
            get {
                return ResourceManager.GetString("UserCanceledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing versions.
        /// </summary>
        public static string VersionCheckString {
            get {
                return ResourceManager.GetString("VersionCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUTORIAL.
        /// </summary>
        public static string VisitHelpString {
            get {
                return ResourceManager.GetString("VisitHelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password, must be at least 6 characters.
        /// </summary>
        public static string WeakPasswordError {
            get {
                return ResourceManager.GetString("WeakPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry..
        /// </summary>
        public static string WeAreSorryString {
            get {
                return ResourceManager.GetString("WeAreSorryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string WelcomeBackString {
            get {
                return ResourceManager.GetString("WelcomeBackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can we do to ensure you love our app? We appreciate your constructive feedback..
        /// </summary>
        public static string WhatCanWeDoString {
            get {
                return ResourceManager.GetString("WhatCanWeDoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are you leaving BioBrain?.
        /// </summary>
        public static string WhyAreYouLeaving {
            get {
                return ResourceManager.GetString("WhyAreYouLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string WomanString {
            get {
                return ResourceManager.GetString("WomanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;p&gt;The word could not be found!&lt;/p&gt;&lt;p&gt;Please check the spelling and try again.&lt;/p&gt;&lt;/html&gt;.
        /// </summary>
        public static string WordNotFoundString {
            get {
                return ResourceManager.GetString("WordNotFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesString {
            get {
                return ResourceManager.GetString("YesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;p class=&quot;correctString&quot;&gt;You are correct!&lt;/p&gt;&lt;/html&gt;.
        /// </summary>
        public static string YouAcirrecrString {
            get {
                return ResourceManager.GetString("YouAcirrecrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;p class=&quot;correctString&quot;&gt;You are correct!&lt;/p&gt;.
        /// </summary>
        public static string YouAreCorrectReplaceString {
            get {
                return ResourceManager.GetString("YouAreCorrectReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY ACCOUNT.
        /// </summary>
        public static string YourAccountString {
            get {
                return ResourceManager.GetString("YourAccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in to Google Play..
        /// </summary>
        public static string YourNotSignedGPString {
            get {
                return ResourceManager.GetString("YourNotSignedGPString", resourceCulture);
            }
        }
    }
}
